name: CI
on:
  push:
    branches:
    - main
    - finish-release-0.1.3
    tags:
    - "v*"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:

  update-packages:
    name: Update packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - uses: coursier/cache-action@v6.3
      - uses: VirtusLab/scala-cli-setup@267af2f1ed4911180b4bb25619ca4a586753cbd1
        with:
          jvm: "temurin:17"
      - uses: webfactory/ssh-agent@fc49353b67b2b7c1e0e6a600572d01a69f2672dd
        with:
          ssh-private-key: |
            ${{ secrets.SCALA_CLI_PACKAGES_KEY }}
            ${{ secrets.HOMEBREW_SCALA_CLI_KEY }}
#      - run: ./mill -i ci.updateInstallationScript
#      - run: ./mill -i ci.updateBrewFormula
      - name: GPG setup
        run: .github/scripts/gpg-setup.sh
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
#      - run: ./mill -i ci.updateDebianPackages
#        env:
#          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
#          GPG_EMAIL: ${{ secrets.GPG_EMAIL }}
#      - run: ./mill -i ci.updateCentOsPackages
#        env:
#          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
#          KEYGRIP: ${{ secrets.KEYGRIP }}
#          PGP_SECRET: ${{ secrets.PGP_SECRET }}
#          GPG_EMAIL: ${{ secrets.GPG_EMAIL }}
#      - run: ./mill -i ci.updateStandaloneLauncher
#        env:
#          UPLOAD_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to SDKMAN
        run: .github/scripts/publish-sdkman.sh
        shell: bash
        env:
          SDKMAN_KEY: ${{ secrets.SDKMAN_KEY }}
          $SDKMAN_TOKEN: ${{ secrets.$SDKMAN_TOKEN }}
