name: CI
on:
  push:
    branches:
    - update-scala-cli-setup
    tags:
    - "v*"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:

  update-packages:
    name: Update packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - uses: coursier/cache-action@v6.3
      - uses: VirtusLab/scala-cli-setup@07b6783a2d71fbf9e834faa234cd51626d76cba5
        with:
          jvm: "temurin:17"
      - uses: webfactory/ssh-agent@fc49353b67b2b7c1e0e6a600572d01a69f2672dd
        with:
          ssh-private-key: |
            ${{ secrets.SCALA_CLI_SETUP_KEY }}
      - run: ./mill -i ci.updateScalaCliSetup
        env:
          UPLOAD_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}