name: CI
on:
  push:
    branches:
    - project-name-virtual-input-test
    tags:
    - "v*"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  jvm-tests:
    timeout-minutes: 120
    runs-on: ${{ matrix.OS }}
    strategy:
      fail-fast: false
      matrix:
        OS: ["ubuntu-latest"]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6.3
    - uses: VirtusLab/scala-cli-setup@07b6783a2d71fbf9e834faa234cd51626d76cba5
      with:
        jvm: "temurin:17"
    - name: JVM integration tests
      run: ./mill -i integration.test.jvm 'scala.cli.integration.RunTestsDefault.pipe scala code and then scala script'

  native-tests:
    timeout-minutes: 120
    runs-on: ${{ matrix.OS }}
    strategy:
      fail-fast: false
      matrix:
        OS: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6.3
    - uses: VirtusLab/scala-cli-setup@07b6783a2d71fbf9e834faa234cd51626d76cba5
      with:
        jvm: "temurin:17"
    - name: Get latest coursier launcher
      run: .github/scripts/get-latest-cs.sh
      shell: bash
      if: runner.os == 'Windows'
    - name: Generate native launcher
      run: .github/scripts/generate-native-image.sh
      shell: bash
    - run: ./mill -i ci.setShouldPublish
    - name: Native integration tests
      run: ./mill -i integration.test.native 'scala.cli.integration.RunTestsDefault.pipe scala code and then scala script'
      env:
        COURSIER_JNI: force
        UPDATE_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  native-static-tests:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6.3
    - uses: VirtusLab/scala-cli-setup@07b6783a2d71fbf9e834faa234cd51626d76cba5
      with:
        jvm: "temurin:17"
    - name: Native integration tests
      run: ./mill -i integration.test.nativeStatic 'scala.cli.integration.RunTestsDefault.pipe scala code and then scala script'
      env:
        UPDATE_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
