name: CI
on:
  push:
    branches:
    - main-test
    tags:
    - "v*"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY_SCALA_CLI }}
    - uses: coursier/cache-action@v6.3
    - uses: VirtusLab/scala-cli-setup@267af2f1ed4911180b4bb25619ca4a586753cbd1
      with:
        jvm: "temurin:17"
    - name: GPG setup
      run: .github/scripts/gpg-setup.sh
      env:
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
    - name: Update stable branch
      uses: devmasx/merge-branch@8b86512c768bec19827894f0a39a776809668189
      with:
        type: now
        message: 'Back port of documentation changes to stable'
        from_branch: main-test
        target_branch: stable
        github_token: ${{ github.token }}