name: CI
on:
  push:
    branches:
    - version-test
    tags:
    - "v*"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  generate-windows-launcher:
    timeout-minutes: 120
    runs-on: "windows-latest"
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - uses: VirtusLab/scala-cli-setup@07b6783a2d71fbf9e834faa234cd51626d76cba5
      with:
        jvm: "temurin:17"
    - name: Get latest coursier launcher
      run: .github/scripts/get-latest-cs.sh
      shell: bash
    - name: Generate native launcher
      run: .github/scripts/generate-native-image.sh
      shell: bash
    - run: ./mill -i ci.setShouldPublish
    - name: Build OS packages
      if: env.SHOULD_PUBLISH == 'true'
      run: .github/scripts/generate-os-packages.sh
      shell: bash
    - name: Copy artifacts
      run: ./mill -i copyDefaultLauncher artifacts/
    - uses: actions/upload-artifact@v3
      with:
        name: windows-launchers
        path: artifacts/
        if-no-files-found: error
        retention-days: 2

  native-windows-tests-3:
    needs: generate-windows-launcher
    timeout-minutes: 120
    runs-on: "windows-latest"
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - uses: VirtusLab/scala-cli-setup@07b6783a2d71fbf9e834faa234cd51626d76cba5
      with:
        jvm: "temurin:17"
    - name: Get latest coursier launcher
      run: .github/scripts/get-latest-cs.sh
      shell: bash
    - uses: actions/download-artifact@v3
      with:
        name: windows-launchers
        path: artifacts/
    - name: Native integration tests
      run: ./mill integration.test.native 'scala.cli.integration.SipScalaTests.*'   
      env:
        COURSIER_JNI: force
        UPDATE_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SCALA_CLI_IT_FORCED_LAUNCHER_DIRECTORY: artifacts/
        SCALA_CLI_IT_GROUP: 3

  