name: CI
on:
  push:
    branches:
      - main
      - test-docker-clang
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:

jobs:

  native-static-tests-1:
    timeout-minutes: 120
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - uses: VirtusLab/scala-cli-setup@9dafe2fb52ed67ee946e5f936d58f9e8b054b270
        with:
          jvm: "temurin:17"
      - name: Build docker image
        run: .github/scripts/generate-docker-image.sh
      - name: Docker integration tests
        run: ./mill integration.docker.test