name: Scala Snippet Checker
on:
  issue_comment:
    types: [created, edited]
  issues:
    types: [opened, edited]

jobs:
  snippet-runner:
    timeout-minutes: 3
    runs-on: "ubuntu-latest"
    steps:
      - uses: virtuslab/scala-snippet-checker@main